version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    env_file: .env
    network_mode: host

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - "zookeeper"
    env_file: .env
    network_mode: host