version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
    container_name: mysql
    env_file: .env
    ports:
      - "3306:3306"

volumes:
  mysql: